[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://87.106.96.173/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/media/*"
  to = "http://87.106.96.173/media/:splat"
  status = 200
  force = true

# Catch-all for SPA client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
